/*
 * This file is generated by jOOQ.
 */
package com.niton.db;


import com.niton.db.tables.Apikey;
import com.niton.db.tables.EdsGroup;
import com.niton.db.tables.Groupmember;
import com.niton.db.tables.Patch;
import com.niton.db.tables.Patchfeature;
import com.niton.db.tables.Task;
import com.niton.db.tables.Users;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>proj_eds</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index APIKEY_PRIMARY = Indexes0.APIKEY_PRIMARY;
    public static final Index EDS_GROUP_FK_GROUP_USERS1 = Indexes0.EDS_GROUP_FK_GROUP_USERS1;
    public static final Index EDS_GROUP_PRIMARY = Indexes0.EDS_GROUP_PRIMARY;
    public static final Index GROUPMEMBER_FK_GROUPMEMBER_USERS1_IDX = Indexes0.GROUPMEMBER_FK_GROUPMEMBER_USERS1_IDX;
    public static final Index GROUPMEMBER_PRIMARY = Indexes0.GROUPMEMBER_PRIMARY;
    public static final Index PATCH_NAME_UNIQUE = Indexes0.PATCH_NAME_UNIQUE;
    public static final Index PATCH_PRIMARY = Indexes0.PATCH_PRIMARY;
    public static final Index PATCHFEATURE_ADDED = Indexes0.PATCHFEATURE_ADDED;
    public static final Index PATCHFEATURE_MODIFYED = Indexes0.PATCHFEATURE_MODIFYED;
    public static final Index PATCHFEATURE_REMOVED = Indexes0.PATCHFEATURE_REMOVED;
    public static final Index TASK_FK_TASK_GROUP1_IDX = Indexes0.TASK_FK_TASK_GROUP1_IDX;
    public static final Index TASK_FK_TASK_USERS1_IDX = Indexes0.TASK_FK_TASK_USERS1_IDX;
    public static final Index TASK_PRIMARY = Indexes0.TASK_PRIMARY;
    public static final Index USERS_FK_USERS_APIKEY_IDX = Indexes0.USERS_FK_USERS_APIKEY_IDX;
    public static final Index USERS_FK_USERS_GROUP1_IDX = Indexes0.USERS_FK_USERS_GROUP1_IDX;
    public static final Index USERS_PRIMARY = Indexes0.USERS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index APIKEY_PRIMARY = Internal.createIndex("PRIMARY", Apikey.APIKEY, new OrderField[] { Apikey.APIKEY.APIKEY_ }, true);
        public static Index EDS_GROUP_FK_GROUP_USERS1 = Internal.createIndex("fk_group_users1", EdsGroup.EDS_GROUP, new OrderField[] { EdsGroup.EDS_GROUP.CREATOR }, false);
        public static Index EDS_GROUP_PRIMARY = Internal.createIndex("PRIMARY", EdsGroup.EDS_GROUP, new OrderField[] { EdsGroup.EDS_GROUP.UID }, true);
        public static Index GROUPMEMBER_FK_GROUPMEMBER_USERS1_IDX = Internal.createIndex("fk_groupmember_users1_idx", Groupmember.GROUPMEMBER, new OrderField[] { Groupmember.GROUPMEMBER.USER }, false);
        public static Index GROUPMEMBER_PRIMARY = Internal.createIndex("PRIMARY", Groupmember.GROUPMEMBER, new OrderField[] { Groupmember.GROUPMEMBER.GROUP, Groupmember.GROUPMEMBER.USER }, true);
        public static Index PATCH_NAME_UNIQUE = Internal.createIndex("name_UNIQUE", Patch.PATCH, new OrderField[] { Patch.PATCH.NAME }, true);
        public static Index PATCH_PRIMARY = Internal.createIndex("PRIMARY", Patch.PATCH, new OrderField[] { Patch.PATCH.VERSION }, true);
        public static Index PATCHFEATURE_ADDED = Internal.createIndex("added", Patchfeature.PATCHFEATURE, new OrderField[] { Patchfeature.PATCHFEATURE.ADDED }, false);
        public static Index PATCHFEATURE_MODIFYED = Internal.createIndex("modifyed", Patchfeature.PATCHFEATURE, new OrderField[] { Patchfeature.PATCHFEATURE.MODIFYED }, false);
        public static Index PATCHFEATURE_REMOVED = Internal.createIndex("removed", Patchfeature.PATCHFEATURE, new OrderField[] { Patchfeature.PATCHFEATURE.REMOVED }, false);
        public static Index TASK_FK_TASK_GROUP1_IDX = Internal.createIndex("fk_task_group1_idx", Task.TASK, new OrderField[] { Task.TASK.GROUP_UID }, false);
        public static Index TASK_FK_TASK_USERS1_IDX = Internal.createIndex("fk_task_users1_idx", Task.TASK, new OrderField[] { Task.TASK.USERS_EMAIL }, false);
        public static Index TASK_PRIMARY = Internal.createIndex("PRIMARY", Task.TASK, new OrderField[] { Task.TASK.NAME, Task.TASK.GROUP_UID, Task.TASK.USERS_EMAIL }, true);
        public static Index USERS_FK_USERS_APIKEY_IDX = Internal.createIndex("fk_users_apikey_idx", Users.USERS, new OrderField[] { Users.USERS.APIKEY }, false);
        public static Index USERS_FK_USERS_GROUP1_IDX = Internal.createIndex("fk_users_group1_idx", Users.USERS, new OrderField[] { Users.USERS.PRIVATE_GROUP }, false);
        public static Index USERS_PRIMARY = Internal.createIndex("PRIMARY", Users.USERS, new OrderField[] { Users.USERS.EMAIL }, true);
    }
}
