/*
 * This file is generated by jOOQ.
 */
package com.niton.db.tables.records;


import com.niton.db.tables.Groupmember;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * The Member of a group defined by his name and permissions
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupmemberRecord extends UpdatableRecordImpl<GroupmemberRecord> implements Record5<Byte, Byte, Byte, Integer, String> {

    private static final long serialVersionUID = -175540660;

    /**
     * Setter for <code>proj_eds.groupmember.edit</code>. Is the user permitted to edit tasks within the group
     */
    public void setEdit(Byte value) {
        set(0, value);
    }

    /**
     * Getter for <code>proj_eds.groupmember.edit</code>. Is the user permitted to edit tasks within the group
     */
    public Byte getEdit() {
        return (Byte) get(0);
    }

    /**
     * Setter for <code>proj_eds.groupmember.create</code>. is the user permitted to create tasks within the Group
     */
    public void setCreate(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>proj_eds.groupmember.create</code>. is the user permitted to create tasks within the Group
     */
    public Byte getCreate() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>proj_eds.groupmember.delete</code>. is the User permitted to delte tasks within the group
     */
    public void setDelete(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>proj_eds.groupmember.delete</code>. is the User permitted to delte tasks within the group
     */
    public Byte getDelete() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>proj_eds.groupmember.group</code>.
     */
    public void setGroup(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>proj_eds.groupmember.group</code>.
     */
    public Integer getGroup() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>proj_eds.groupmember.user</code>.
     */
    public void setUser(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>proj_eds.groupmember.user</code>.
     */
    public String getUser() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Byte, Byte, Byte, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Byte, Byte, Byte, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field1() {
        return Groupmember.GROUPMEMBER.EDIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return Groupmember.GROUPMEMBER.CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return Groupmember.GROUPMEMBER.DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Groupmember.GROUPMEMBER.GROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Groupmember.GROUPMEMBER.USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component1() {
        return getEdit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component2() {
        return getCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getGroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value1() {
        return getEdit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getGroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupmemberRecord value1(Byte value) {
        setEdit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupmemberRecord value2(Byte value) {
        setCreate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupmemberRecord value3(Byte value) {
        setDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupmemberRecord value4(Integer value) {
        setGroup(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupmemberRecord value5(String value) {
        setUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupmemberRecord values(Byte value1, Byte value2, Byte value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupmemberRecord
     */
    public GroupmemberRecord() {
        super(Groupmember.GROUPMEMBER);
    }

    /**
     * Create a detached, initialised GroupmemberRecord
     */
    public GroupmemberRecord(Byte edit, Byte create, Byte delete, Integer group, String user) {
        super(Groupmember.GROUPMEMBER);

        set(0, edit);
        set(1, create);
        set(2, delete);
        set(3, group);
        set(4, user);
    }
}
