/*
 * This file is generated by jOOQ.
 */
package com.niton.db.routines;


import com.niton.db.ProjEds;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getnewgroupuid extends AbstractRoutine<String> {

    private static final long serialVersionUID = -702806300;

    /**
     * The parameter <code>proj_eds.getNewGroupUID.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.VARCHAR(30), false, false);

    /**
     * Create a new routine call instance
     */
    public Getnewgroupuid() {
        super("getNewGroupUID", ProjEds.PROJ_EDS, org.jooq.impl.SQLDataType.VARCHAR(30));

        setReturnParameter(RETURN_VALUE);
    }
}
