/*
 * This file is generated by jOOQ.
 */
package com.niton.db.routines;


import com.niton.db.ProjEds;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Log extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 873883152;

    /**
     * The parameter <code>proj_eds.log.msg</code>.
     */
    public static final Parameter<String> MSG = Internal.createParameter("msg", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public Log() {
        super("log", ProjEds.PROJ_EDS);

        addInParameter(MSG);
    }

    /**
     * Set the <code>msg</code> parameter IN value to the routine
     */
    public void setMsg(String value) {
        setValue(MSG, value);
    }
}
