/*
 * This file is generated by jOOQ.
 */
package com.niton.db.routines;


import com.niton.db.ProjEds;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Updatetask extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1597405651;

    /**
     * The parameter <code>proj_eds.updateTask.nprocess</code>.
     */
    public static final Parameter<Integer> NPROCESS = Internal.createParameter("nprocess", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>proj_eds.updateTask.ndeadline</code>.
     */
    public static final Parameter<Date> NDEADLINE = Internal.createParameter("ndeadline", org.jooq.impl.SQLDataType.DATE, false, false);

    /**
     * The parameter <code>proj_eds.updateTask.nplanedDate</code>.
     */
    public static final Parameter<Date> NPLANEDDATE = Internal.createParameter("nplanedDate", org.jooq.impl.SQLDataType.DATE, false, false);

    /**
     * The parameter <code>proj_eds.updateTask.ndescription</code>.
     */
    public static final Parameter<String> NDESCRIPTION = Internal.createParameter("ndescription", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>proj_eds.updateTask.groupuid</code>.
     */
    public static final Parameter<String> GROUPUID = Internal.createParameter("groupuid", org.jooq.impl.SQLDataType.VARCHAR(30), false, false);

    /**
     * The parameter <code>proj_eds.updateTask.name</code>.
     */
    public static final Parameter<String> NAME = Internal.createParameter("name", org.jooq.impl.SQLDataType.VARCHAR(50), false, false);

    /**
     * Create a new routine call instance
     */
    public Updatetask() {
        super("updateTask", ProjEds.PROJ_EDS);

        addInParameter(NPROCESS);
        addInParameter(NDEADLINE);
        addInParameter(NPLANEDDATE);
        addInParameter(NDESCRIPTION);
        addInParameter(GROUPUID);
        addInParameter(NAME);
    }

    /**
     * Set the <code>nprocess</code> parameter IN value to the routine
     */
    public void setNprocess(Integer value) {
        setValue(NPROCESS, value);
    }

    /**
     * Set the <code>ndeadline</code> parameter IN value to the routine
     */
    public void setNdeadline(Date value) {
        setValue(NDEADLINE, value);
    }

    /**
     * Set the <code>nplanedDate</code> parameter IN value to the routine
     */
    public void setNplaneddate(Date value) {
        setValue(NPLANEDDATE, value);
    }

    /**
     * Set the <code>ndescription</code> parameter IN value to the routine
     */
    public void setNdescription(String value) {
        setValue(NDESCRIPTION, value);
    }

    /**
     * Set the <code>groupuid</code> parameter IN value to the routine
     */
    public void setGroupuid(String value) {
        setValue(GROUPUID, value);
    }

    /**
     * Set the <code>name</code> parameter IN value to the routine
     */
    public void setName_(String value) {
        setValue(NAME, value);
    }
}
